name: weather_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.1.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  rive: ^0.12.4
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  go_router: ^13.0.0

  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/rive/
    - assets/lottie/
    - assets/background_image/

